simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>STORMBIRD</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">
            <img src="/static/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            STORMBIRD
          </a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}

            <button type="button" class="btn btn-success"><a class="nav-item nav-link" href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></button>
            <button type="button" class="btn btn-info"><a class="nav-item nav-link" href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></button>
            <button type="button" class="btn btn-info"><a class="nav-item nav-link" href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></button>
            <button type="button" class="btn btn-warning"><a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></button>


          {% else %}
            <button type="button" class="btn btn-danger"><a class="nav-item nav-link" href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></button>
            <button type="button" class="btn btn-info"><a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></button>
            <button type="button" class="btn btn-warning "><a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></button>

          {% endif %}
        </div>
      </div>
    </nav>

    <div class="top">
      <p>d</p>
      <p>d</p>

    </div>

    {% block contentIndex %}

    {% endblock %}

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <div class="bot">
      <p>d</p>
        <p>d</p>

    </div>


    <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}
{% block contentIndex %}



  <div class="container">
      <div class="jumbotron">
        <h1 class="display-4">Welcome to STORMBIRD!</h1>
        <p class="lead">Let's start sharing your moment</p>
        <hr class="my-4">
        <p>Making your life simple, free sign up !!!</p>
        <a class="btn btn-info btn-lg" href="{% url 'accounts:signup' %}" role="button">Sign Up now!</a>
      </div>
    </div>
  </div>

  <div class="container card text-center">
  <div class="card-header">
    <span class="badge badge-warning">Featured</span>

    <span class="badge badge-dark">Posting moment</span>
    <span class="badge badge-dark">Join Groups</span>
    <span class="badge badge-dark">Create Groups</span>

  </div>
  <div class="card-body">
    <h5 class="card-title">Get started now! with 3 simple step to follow</h5>
    <p class="card-text"></p>
    <a href="{% url 'accounts:signup' %}" class="btn btn-info btn-sm">Sign up</a>
  </div>

</div>


  <div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="cc card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">STEP 1 : SIGN UP </h5>
    <p class="card-text"></p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="cc card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">STEP 2 : LOGIN</h5>
    <p class="card-text"></p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="cc card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">STEP 3 : POSTING MOMENT</h5>
    <p class="card-text"></p>
  </div>
</div>
    </div>
  </div>
</div>







{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Well done!</h4>
  <p>You are now logged in!</p>
  <hr>
</div>

<div class="container">

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-5">Hello!!! @{{user.username }} what you gonna share today?</h1>
    </div>
  </div>



  <div class="row">
  <div class="col-8">
  <ul class="list-group">
    <li class="list-group-item list-group-item-primary"><h4><a href="{% url 'posts:for_user' username=user.username %}">View status</a></h4></li>
    <li class="list-group-item list-group-item-warning"><h4><a href="{% url 'posts:create' %}">Update status</a></h4></li>
    <li class="list-group-item list-group-item-danger"><h4><a href="{% url 'groups:all'%}">View Groups</a></h4></li>
    <li class="list-group-item list-group-item-secondary"><h4><a href="{% url 'groups:create' %}">Create Groups</a></h4></li>
  </ul>
</div>
  <div class="col-4">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/b.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/a.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/c.jpg" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  </div>
</div>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-6">Today's Quotes</h1>
    <p class="lead">| Sometimes we’re tested not to show our weaknesses, but to discover our strengths. | </p>
  </div>
</div>


</div>

{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Thanks for visiting! Come back soon!</h4>
</div>

<div class="container">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to STORMBIRD!</h1>
      <p class="lead">Let's start sharing your moment</p>
      <hr class="my-4">
      <p>Making your life simple, free sign up !!!</p>
      <a class="btn btn-info btn-lg" href="{% url 'accounts:signup' %}" role="button">Sign Up now!</a>
    </div>
  </div>
</div>

<div class="container card text-center">
<div class="card-header">
  <span class="badge badge-warning">Featured</span>

  <span class="badge badge-dark">Posting moment</span>
  <span class="badge badge-dark">Join Groups</span>
  <span class="badge badge-dark">Create Groups</span>

</div>
<div class="card-body">
  <h5 class="card-title">Get started now! with 3 simple step to follow</h5>
  <p class="card-text"></p>
  <a href="{% url 'accounts:signup' %}" class="btn btn-info btn-sm">Sign up</a>
</div>

</div>


<div class="container">
<div class="row">
  <div class="col-sm">
    <div class="cc card text-center" style="width: 18rem;">
<div class="card-body">
  <h5 class="card-title">STEP 1 : SIGN UP </h5>
  <p class="card-text"></p>
</div>
</div>
  </div>
  <div class="col-sm">
    <div class="cc card text-center" style="width: 18rem;">
<div class="card-body">
  <h5 class="card-title">STEP 2 : LOGIN</h5>
  <p class="card-text"></p>
</div>
</div>
  </div>
  <div class="col-sm">
    <div class="cc card text-center" style="width: 18rem;">
<div class="card-body">
  <h5 class="card-title">STEP 3 : POSTING MOMENT</h5>
  <p class="card-text"></p>
</div>
</div>
  </div>
</div>
</div>



{% endblock %}